name: 'Bark Action'
description: 'An action for bark'
author: 'Yaojian Li'
branding:
  icon: 'message-circle'
  color: 'red'
inputs:
  key:
    description: Secret key
    required: true
  host:
    description: Bark server hostname
    required: false
  title:
    description: Message title
    required: false
  body:
    description: Message body
    required: false
  url:
    description: URL to redirect
    required: false
runs:
  using: "composite"
  steps:
    - name: Run script
      shell: bash
      run: $GITHUB_ACTION_PATH/script.sh
      env:
        INPUT_KEY: ${{ inputs.key }}
        INPUT_HOST: ${{ inputs.host }}
        INPUT_TITLE: ${{ inputs.title }}
        INPUT_BODY: ${{ inputs.body }}
        INPUT_URL: ${{ inputs.url }}
